module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  authorised_email_registration: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_mentions: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dpc_multistage_signup: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  gnode: 0
  grequest: 0
  group: 0
  help: 0
  history: 0
  image: 0
  innovation_network_groups: 0
  innovation_network_redirects: 0
  innovation_network_site: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  kint: 0
  link: 0
  link_attributes: 0
  mailsystem: 0
  media: 0
  media_library: 0
  menu_item_extras: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  node_view_permissions: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  r4032login: 0
  rabbit_hole: 0
  rdf: 0
  realname: 0
  rh_node: 0
  saml_sp: 0
  saml_sp_drupal_login: 0
  search_api: 0
  search_api_db: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  user: 0
  user_field_value: 0
  variationcache: 0
  views_contextual_filters_or: 0
  views_infinite_scroll: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_group: 0
  webform_node: 0
  webform_ui: 0
  webprofiler: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  innovation_network: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
