idp:
  localhost: localhost
logout: false
update_email: false
update_language: false
no_account_authenticated_user_role: false
no_account_authenticated_user_account: null
force_saml_only: false
account_request_request_account: false
account_request_site_mail: false
account_request_site_administrators:
  1: 0
